# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d827fae91f22005312bd3d2fea8c1807c233f079723df44c677d6b0a2eb0563bd7614fef45469b63d2f3e690f3b65712d914fad3f3862e708aeb4c19a7f639df

test:
  secret_key_base: fc2467196a8dadcfaccc195ab255b62a671cfd5761eae23656d1f221c605476ee3451b8b594c09df086746bc8acf27661fbcc848ec8658416918ff0e4f56292a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
